language: python

sudo: required

#Pre-install packages for the ubuntu distribution
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
    - NIBABEL=nibabel

python:
    - "3.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/bin/activate root
  - conda update --yes conda

# Install packages
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pandas
    - pip install -r requirements.txt
    - pip install nose
    - pip install codecov
    - pip install dipy
    - pip install termcolor
    - pip install $NIBABEL
    - python setup.py build_ext --inplace

# command to run tests
script: 
    - nosetests -v --with-coverage
    - codecov -t 4896b116-68c2-4b70-9a47-57c6d529483c
